.Dd dec 10, 2021
.Dt MAILTUBE 1
.Os
.
.
.Sh NAME
.
.Nm mailtube-server ,
.Nm mailtube-xnotify ,
.Nm mailtube-herbe
.Nd scan a Maildir an send notifications to xnotify
.
.
.Sh SYNOPSIS
.
.Nm mailtube-server
.Op Fl v
.Op Fl s Ar freq
.Ar dir
.
.Nm mailtube-client
.Op Fl v
.Ar server-command...
.
.
.Sh DESCRIPTION
.
.Pp
.Nm mailtube-server
discovers Maildirs subdirectories of
.Ar dir
and scans for mails in the
.Pa new
directory.
For every new mail encountered, a notification message is sent to
stdout with the name of the file, and one line per header (not all
headers are shown).
Then, the mail is moved to the
.Pa cur
directory.
.
.Bl -tag
.
.It Fl v
Get the version.
.
.It Fl s
Sets the scan frequency at which the Maildir tree is scanned for
new directories and new messages.
.
.El
.
.
.Pp
.Nm mailtube-client
executes a command, usually
.Nm mailtube-server ,
and send a notification for each message from mailtube-server to the desktop.
.
.Pp
Instead of invoking mailtube-client directly, the actual client are named
.Nm mailtube-xnotify
and
.Nm mailtube-herbe
.
.Bl -tag
.
.It Fl v
Get the version.
.
.El
.
.Sh CLIENT FRONTENDS
.
.Pp
Various clients can be used interchangably.
To build a new client frontend add an entry to
.Va CLIENTS
in the
.Pa Makefile ,
then add a mailtube-clientname.c file with at least:
.
.Bl -tag
.
.It Ft void Fn init_notifications "void"
Called first befor any notification is sent.
.
.It Ft void Fn send_notification_path "char *mail"
Called at the start of a new notification, with the path to the
mail on the Maildir, to use as an action for the notification.
.
.It Ft void Fn send_notification_header "char *header"
Called for each header of mail, to show on the notification.
.
.It Ft void Fn send_notification_end "void"
Called last, for actually sending the notification.
.
.El
.
.
.Sh ENVIRONMENT
.
.Bl -tag 6n
.
.It Ev XNOTIFY_FIFO
Contains a path to 
.Xr xnotify 1
FIFO, to which
.Nm mailtube-xnotify
will send the notifications messages.
.
.It Ev DISPLAY
Used by most X11 programs to select the display, including
.Xr herbe 1
and
.Xr xnotify 1 .
.
.El
.
.
.Sh EXAMPLES
.
.Pp
Send a notification for every mail received in a local Maildir directory:
.Bd -literal
$ mailtube-xnotify mailtube-server Maildir
.Ed
.
.Pp
The same, but with a remote maildir, over SSH:
.Bd -literal
$ mailtube-xnotify ssh user@example.org mailtube-server Maildir
.Ed
.
.
.Sh CAVEATS
.
If an IMAP daemon is run on the same server, it may race to get the new mails.
This can be worked around, by not scanning the same directories as
.Nm .
.
.
.Sh SEE ALSO
.
.Xr xnotify 1
.
.
.Sh AUTHORS
.
Josuah Demangeon <me@josuah.net>
